---
  - name: test my module
    hosts: localhost
    tasks:
    - name  : run my module
      netology.files.create_file:
        path: "/tmp/file.txt"
        content: "some new content"
      register: test_out
    - name: dump test_out
      debug:
        msg: "{{ test_out }}"  